defaults:
  - _self_
  - hydra: settings

version: 0.1.0
name: ${version}-f1-mvp

data_sources:
  huc_boundary: /Users/taddbindas/projects/NGWPC/f1_trainer/data/boundaries/11070103_huc.gpkg
  observations: /Users/taddbindas/projects/NGWPC/f1_trainer/data/sentinel/cloud_cutout_extent_filled_optimized.tif

np_seed: 1
seed: 0
device: mps:0
